# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
# Pinned SHAs for cross-repo catalog drift CI (external-runtime TOML format).
# Bump only after umst-formal-double-slit export regen + manifold lock update.
# Protocol: docs/CATALOG_UPDATE_PROTOCOL.md

[umst-formal-double-slit]
sha = "51615ce79bc5ecd14de82d358aacd19a2ba11d61"
pinned_at = "2026-10-02T23:57:32Z"
repo = "https://github.com/tytolabs/umst-formal-double-slit"

[umst-formal]
sha = "7c85e0439bb7f2b67ff79327ad6289e4dd392b8f"
pinned_at = "2026-10-02T23:57:32Z"
repo = "https://github.com/tytolabs/umst-formal"

[umst-foundations]
sha = "85bda074c1a34788f60210d09c15e22ac76b0e74"
repo = "https://github.com/tytolabs/umst-foundations"

[umst-cartridge-api]
sha = "cfb27d2efad3f458dc5ac3d55581ef81f86a6705"
repo = "https://github.com/tytolabs/umst-cartridge-api"

[umst-cartridges]
sha = "cdf3eeb43dfced32746e74020cc926a0a1a2d2ab"
repo = "https://github.com/tytolabs/umst-cartridges"
