// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Santhosh Shyamsundar, Santosh Prabhu Shenbagamoorthy — Studio TYTO

//! Two build-time payloads:
//!
//! 1. **Lean / lock bundle** — `artifacts/catalog.lock.json` (or `UMST_CATALOG`). Emits the
//!    `UMST_CATALOG_LOCK_SHA256_HEX` rustc env consumed by [`catalog_lock_bundle_sha256_hex`].
//! 2. **Witness catalog JSON envelope** (`WitnessCatalog`) — emits `OUT_DIR/catalog_constants.rs`
//!    containing a SHA-256 fingerprint and a `[u8; N]` array. When no witness JSON exists on disk,
//!    a minimal built-in envelope is embedded so **`cargo check` never requires extra files.**

use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

/// Minimal envelope when neither `witness_catalog.json` nor `UMST_CATALOG_BUILD_JSON` exist.
const WITNESS_CATALOG_FALLBACK_JSON: &str = r#"{"version":1,"witnesses":[{"id":"umst.catalog.builtin.min","description":"build.rs fallback (no witness_catalog.json)"}]}"#;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));

    emit_catalog_lock_digest(&manifest_dir);
    let witness_bytes = resolve_witness_catalog_bytes(&manifest_dir);
    write_catalog_constants(&out_dir, &witness_bytes);
}

fn emit_catalog_lock_digest(manifest_dir: &Path) {
    let rel = env::var("UMST_CATALOG").unwrap_or_else(|_| "artifacts/catalog.lock.json".into());
    let path = if PathBuf::from(&rel).is_absolute() {
        PathBuf::from(rel)
    } else {
        manifest_dir.join(rel)
    };

    println!("cargo:rerun-if-env-changed=UMST_CATALOG");
    println!("cargo:rerun-if-changed={}", path.display());

    let (hex, upstream_hex) = match fs::read_to_string(&path) {
        Ok(raw) => {
            let bundle = Sha256::digest(raw.as_bytes());
            let bundle_hex = format!("{bundle:x}");
            let upstream_hex = parse_lock_upstream_digest_hex(&raw).unwrap_or_else(|| {
                println!(
                    "cargo:warning=umst-manifold: catalog lock at {} missing upstream_catalog_digest_hex — using zero upstream digest",
                    path.display()
                );
                "0".repeat(64)
            });
            (bundle_hex, upstream_hex)
        }
        Err(e) => {
            println!(
                "cargo:warning=umst-manifold: catalog lock missing at {} — using zero digest ({})",
                path.display(),
                e
            );
            let zeros = "0".repeat(64);
            (zeros.clone(), zeros)
        }
    };

    println!("cargo:rustc-env=UMST_CATALOG_LOCK_SHA256_HEX={hex}");
    println!("cargo:rustc-env=UMST_LOCK_UPSTREAM_CATALOG_DIGEST_HEX={upstream_hex}");
}

/// v2 `composed_catalog_digest_hex` or v1 `upstream_catalog_digest_hex` from lock JSON.
fn parse_lock_upstream_digest_hex(lock_json: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(lock_json).ok()?;
    let hex = v
        .get("composed_catalog_digest_hex")
        .or_else(|| v.get("upstream_catalog_digest_hex"))?
        .as_str()?;
    if hex.len() == 64 && hex.bytes().all(|b| b.is_ascii_hexdigit()) {
        Some(hex.to_ascii_lowercase())
    } else {
        None
    }
}

fn resolve_witness_catalog_bytes(manifest_dir: &Path) -> Vec<u8> {
    println!("cargo:rerun-if-env-changed=UMST_CATALOG_BUILD_JSON");
    println!("cargo:rerun-if-changed=witness_catalog.json");

    if let Ok(p) = env::var("UMST_CATALOG_BUILD_JSON") {
        let path = PathBuf::from(&p);
        return fs::read(&path).unwrap_or_else(|e| {
            panic!(
                "UMST_CATALOG_BUILD_JSON points at {} but cannot be read: {e}",
                path.display()
            );
        });
    }

    let default_path = manifest_dir.join("witness_catalog.json");
    if default_path.is_file() {
        return fs::read(&default_path).unwrap_or_else(|e| {
            panic!(
                "failed reading witness catalog at {}: {e}",
                default_path.display()
            );
        });
    }

    WITNESS_CATALOG_FALLBACK_JSON.as_bytes().to_vec()
}

fn write_catalog_constants(out_dir: &Path, bytes: &[u8]) {
    let digest = Sha256::digest(bytes);
    let hex = format!("{digest:x}");
    let len = bytes.len();

    let path = out_dir.join("catalog_constants.rs");
    let mut f = fs::File::create(&path).expect("catalog_constants.rs");
    writeln!(
        f,
        "// @generated by build.rs\n\
/// SHA-256 (hex, lowercase) of embedded witness-catalog JSON.\n\
pub const WITNESS_CATALOG_EMBEDDED_SHA256_HEX: &str = \"{hex}\";\n\
/// Byte length of [`WITNESS_CATALOG_EMBEDDED_BYTES`].\n\
pub const WITNESS_CATALOG_EMBEDDED_LEN: usize = {len};\n\
pub static WITNESS_CATALOG_EMBEDDED_BYTES: [u8; {len}] = ["
    )
    .expect("write");

    for (i, b) in bytes.iter().enumerate() {
        if i % 16 == 0 {
            write!(f, "\n    ").expect("write");
        }
        write!(f, "{b}, ").expect("write");
    }
    writeln!(f, "\n];").expect("write");
}
