// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Santhosh Shyamsundar, Santosh Prabhu Shenbagamoorthy — Studio TYTO

use std::fmt::Write as _;

use crate::parse::LayoutSpec;

/// Emit `SCALAR_*` column index constants and [`UMST_SCALAR_CHANNEL_COUNT`].
pub fn emit_scalar_layout_rs(spec: &LayoutSpec) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "// @generated by umst-layout-codegen — do not edit\n\
/// Pinned nodal scalar channel count (`artifacts/scalar_layout.lock.json`)."
    )
    .expect("fmt");
    writeln!(
        out,
        "pub const UMST_SCALAR_CHANNEL_COUNT: usize = {};",
        spec.scalar_channel_count
    )
    .expect("fmt");
    writeln!(out).expect("fmt");

    for (index, id) in spec.channel_ids.iter().enumerate() {
        writeln!(out, "/// Column index `{index}`: `{id}`.").expect("fmt");
        writeln!(out, "pub const {id}: usize = {index};").expect("fmt");
        writeln!(out).expect("fmt");
    }

    out
}

/// Emit lock-file channel count for drift guard (`UMST_SCALAR_CHANNEL_COUNT_LOCK`).
pub fn emit_scalar_layout_guard(spec: &LayoutSpec) -> String {
    format!(
        "// @generated by build.rs via umst-layout-codegen — do not edit\n\
/// Lock-file scalar channel count (must match [`super::UMST_SCALAR_CHANNEL_COUNT`]).\n\
pub const UMST_SCALAR_CHANNEL_COUNT_LOCK: usize = {};",
        spec.scalar_channel_count
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_scalar_layout_lock;

    #[test]
    fn emit_scalar_indices_from_lock() {
        let json = r#"{
  "schema": "umst_scalar_layout_v1",
  "scalar_channel_count": 2,
  "channel_ids": ["SCALAR_CHANNEL0", "SCALAR_HUMIDITY"]
}"#;
        let spec = parse_scalar_layout_lock(json).unwrap();
        let emitted = emit_scalar_layout_rs(&spec);

        assert!(emitted.contains("pub const UMST_SCALAR_CHANNEL_COUNT: usize = 2;"));
        assert!(emitted.contains("pub const SCALAR_CHANNEL0: usize = 0;"));
        assert!(emitted.contains("pub const SCALAR_HUMIDITY: usize = 1;"));
    }
}
