// SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
// SPDX-License-Identifier: MIT
//
//! `umst-runtime` — executor crate (A3 alias of workspace-root `umst-manifold` during transition).
//!
//! New code should depend on `umst-runtime`; legacy path deps on `umst-manifold` remain valid via the
//! root facade package until the GitHub rename + `crates/umst-manifold` facade swap (see A3 status doc).

#![allow(deprecated)]

pub mod burn_algebra_adapter_posture;
pub mod burn_algebra_ops_posture;
pub mod burn_algebra_posture;
#[cfg(feature = "nalgebra-tensor")]
pub mod nalgebra_algebra_posture;
pub mod num_dual_ad_posture;

pub use burn_algebra_adapter_posture::{
    ADAPTER_CRATE_LANDED as BURN_ADAPTER_CRATE_LANDED,
    ADAPTER_CRATE_PATH as BURN_ADAPTER_CRATE_PATH,
    ADAPTER_SCAFFOLD_LANDED as BURN_ADAPTER_SCAFFOLD_LANDED,
    DESIGN_DOC_PATH as BURN_ADAPTER_DESIGN_DOC, PARENT_RESIDUE_ID as BURN_ADAPTER_PARENT_ID,
    PBM_ID as BURN_ADAPTER_PBM_ID, POSTURE_TAG as BURN_ADAPTER_POSTURE,
    PRIOR_RECEIPT_SLUG as BURN_ADAPTER_PRIOR_RECEIPT,
    RANK1_PLUS_IMPL_LANDED as BURN_ADAPTER_RANK1_IMPL_LANDED, RECEIPT_SLUG as BURN_ADAPTER_RECEIPT,
    SLICE3B_LEDGER_PATH as BURN_ADAPTER_SLICE3B_LEDGER_PATH,
    SLICE3C_ADAPTER_PATH as BURN_ADAPTER_SLICE3C_PATH, SLICE_ID as BURN_ADAPTER_SLICE_ID,
};
pub use burn_algebra_posture::{
    DESIGN_DOC_PATH as BURN_ALGEBRA_DESIGN_DOC, LIFT_STEP_LANDED as BURN_ALGEBRA_LIFT_STEP_LANDED,
    PARENT_RESIDUE_ID as BURN_ALGEBRA_PARENT_ID, PBM010_ID as BURN_ALGEBRA_PBM010_ID,
    PBM010_RECEIPT_SLUG as BURN_ALGEBRA_PBM010_RECEIPT,
    PBM010_SLICE_RESIDUAL_RECEIPT_SLUG as BURN_ALGEBRA_PBM010_SLICE_RESIDUAL_RECEIPT,
    PBM_ID as BURN_ALGEBRA_PBM_ID, POSTURE_TAG as BURN_ALGEBRA_POSTURE,
    PRODUCTION_LANDED as BURN_ALGEBRA_PRODUCTION_LANDED,
    RANK1_PLUS_LEDGER_LANDED as BURN_ALGEBRA_RANK1_LEDGER_LANDED,
    RANK1_PLUS_LIFT_LANDED as BURN_ALGEBRA_RANK1_LIFT_LANDED,
    RECEIPT_SLUG as BURN_ALGEBRA_RECEIPT_SLUG, R_ATOMS_SCALAR_ID as BURN_ALGEBRA_R_ATOMS_SCALAR_ID,
    SLICE2_PROTOTYPE_LANDED, SLICE2_PROTOTYPE_PATH, SLICE2_WITNESS_PATH,
    SLICE3B_ID as BURN_ALGEBRA_SLICE3B_ID, SLICE3B_LEDGER_PATH as BURN_ALGEBRA_SLICE3B_LEDGER_PATH,
    SLICE3_ADAPTER_PATH, SLICE3_LIFT_STEP_PATH, SLICE_ID as BURN_ALGEBRA_SLICE_ID,
    SLICE_RESIDUAL_PATH as BURN_ALGEBRA_SLICE_RESIDUAL_PATH,
    SLICE_RESIDUAL_ROWS_LANDED as BURN_ALGEBRA_SLICE_RESIDUAL_LANDED,
};
#[cfg(feature = "nalgebra-tensor")]
pub use nalgebra_algebra_posture::{
    BLUEPRINT_ROW as NALGEBRA_ALGEBRA_BLUEPRINT_ROW,
    CARTRIDGE_LIFT_LANDED as NALGEBRA_ALGEBRA_CARTRIDGE_LIFT_LANDED,
    DESIGN_DOC_PATH as NALGEBRA_ALGEBRA_DESIGN_DOC, LIB_ID as NALGEBRA_ALGEBRA_LIB_ID,
    NUM_DUAL_LANDED as NALGEBRA_ALGEBRA_NUM_DUAL_LANDED,
    PARENT_RESIDUE_ID as NALGEBRA_ALGEBRA_PARENT_ID, POSTURE_TAG as NALGEBRA_ALGEBRA_POSTURE,
    RECEIPT_SLUG as NALGEBRA_ALGEBRA_RECEIPT, RESEARCH_DOC_PATH as NALGEBRA_ALGEBRA_RESEARCH_DOC,
    SCAFFOLD_LANDED as NALGEBRA_ALGEBRA_SCAFFOLD_LANDED,
    SLICE4_SCAFFOLD_PATH as NALGEBRA_ALGEBRA_SLICE4_PATH, SLICE_ID as NALGEBRA_ALGEBRA_SLICE_ID,
};
pub use num_dual_ad_posture::{
    CONTINUUM_MODULE_PATH as NUM_DUAL_CONTINUUM_MODULE_PATH, F09_NALGEBRA_ID as NUM_DUAL_F09_ID,
    FEATURE_GATE as NUM_DUAL_FEATURE_GATE,
    INTEGRATION_WITNESS_PATH as NUM_DUAL_INTEGRATION_WITNESS_PATH, NUM_DUAL_CRATE_PIN,
    PARENT_RESIDUE_ID as NUM_DUAL_PARENT_RESIDUE_ID, PBM_ID as NUM_DUAL_PBM_ID,
    POSTURE_TAG as NUM_DUAL_POSTURE, RECEIPT_SLUG as NUM_DUAL_RECEIPT_SLUG,
    RESEARCH_RECEIPT as NUM_DUAL_RESEARCH_RECEIPT, SCALAR_AD_LANDED as NUM_DUAL_SCALAR_AD_LANDED,
    SLICE_ID as NUM_DUAL_SLICE_ID, TENSOR_LIFT_LANDED as NUM_DUAL_TENSOR_LIFT_LANDED,
};
pub use umst_manifold::*;
